### ISSUE TITLE
What did you end up doing for Mediawiki SSO in Discourse?

### ISSUE THREAD

**Issue by sunjam** [tgr/discourse-mediawiki#1]
Curious on if you found a different solution.

**Comment by tgr** [comment]
Yes! This project never got anywhere but a similar plugin was written by someone who actually knows how to write Discourse plugins: [paviliondev/discourse-wikimedia-auth](https://github.com/paviliondev/discourse-wikimedia-auth).

[discourse-mediawiki.wmflabs.org](https://discourse-mediawiki.wmflabs.org/) uses that now.
